sudo: required
services:
  - docker

before_install:
  - docker build -t mdhanapal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mdhanapal/react-test npm test

after_success:
  - docker build -t mdhanapal/multi-client ./client
  - docker build -t mdhanapal/multi-nginx ./nginx
  - docker build -t mdhanapal/multi-server ./server
  - docker build -t mdhanapal/multi-worker ./worker
  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push to docker hub

  - docker push mdhanapal/multi-client
  - docker push mdhanapal/multi-nginx
  - docker push mdhanapal/multi-server
  - docker push mdhanapal/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-183397191605
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
